---   
 http://docs.cloudstack.apache.org/projects/cloudstack-installation/en/4.9/management-server/index.html
- name: Create /etc/yum.repos.d/cloudstack.repo
  copy:
    src: cloudstack.repo
    dest: /etc/yum.repos.d/cloudstack.repo
    
- name: Install http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
  yum:
    name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    state: present

- name: Install epel-release
  package:
    name: epel-release
    state: latest  

#- name: Install http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#  yum:
#    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#    state: present

- name: Install cloudstack-management
  package:
    name: cloudstack-management
    state: latest
    
- name: Install mysql-server
  package:
    name: mysql-server
    state: latest

- name: Install MySQL-python
  package:
    name: MySQL-python
    state: latest
    
#yum -y update
#reboot

- name: /etc/cloudstack/management/commons-logging.properties -> /etc/cloudstack/management/logging.properties
  file:
    src: /etc/cloudstack/management/commons-logging.properties
    dest: /etc/cloudstack/management/logging.properties
    state: link

- name: Create /etc/my.cnf
  copy:
    src: my.cnf
    dest: /etc/my.cnf 

- name: Start MySQL
  systemd:
    enabled: yes
    state: started
    name: mysql

- name: Set root password
  mysql_user: name=root host={{item}} password={{cs_master_password | mandatory}} state=present
  with_items:
    - '::1'
    - '127.0.0.1'
    - 'localhost'
  ignore_errors: yes    
    
- name: Run cloudstack-setup-databases 
  shell: "cloudstack-setup-databases cloud:{{ cs_master_password }}@localhost --deploy-as=root:{{ cs_master_password }} -m {{ cs_master_password }} -k {{ cs_master_password }}"
  register: cloudstack-setup-databases_output

- name: Run cloudstack-setup-databases output
  debug: msg="{{ cloudstack-setup-databases_output.stdout }}"

- name: Run cloudstack-setup-databases error
  debug: msg="{{ cloudstack-setup-databases_output.stderr }}"   

#cat >> /etc/sudoers <<EOF
#Defaults:cloud !requiretty
#EOF

- name: Run cloudstack-setup-management --tomcat7 
  shell: "cloudstack-setup-management --tomcat7"
  register: cloudstack-setup-management_output

- name: Run cloudstack-setup-management output
  debug: msg="{{ cloudstack-setup-management_output.stdout }}"

- name: Run cloudstack-setup-management error
  debug: msg="{{ cloudstack-setup-management_output.stderr }}"   
  
    
- name: Install nfs-utils
  package:
    name: nfs-utils
    state: latest

- name: /export/primary
  file: 
    path: /export/primary
    state: directory  

- name: /export/secondary
  file: 
    path: /export/secondary
    state: directory  

- name: Create /etc/exports
  copy:
    src: exports
    dest: /etc/exports

- name: Run exportfs -a
  shell: "exportfs -a"

- name: Create /etc/sysconfig/nfs
  copy:
    src: sysconfig-nfs
    dest: /etc/sysconfig/nfs
  
- name: Create /etc/idmapd.conf
  copy:
    src: idmapd.conf
    dest: /etc/idmapd.conf

- name: Start rpcbind
  systemd:
    enabled: yes
    state: started
    name: rpcbind
    
- name: Start nfs
  systemd:
    enabled: yes
    state: started
    name: nfs
    
